#!/bin/bash



# Autobash
alias srcbash='source ~/.bashrc'
alias edit-bash=$EDITOR' ~/.bashrc ~/.bash_aliases'
alias edit-bashaliases=$EDITOR' ~/.bash_aliases'
alias edit-bashrc=$EDITOR' ~/.bashrc'
alias anaconda3='bash --rcfile ~/.conda_bashrc3'
alias tolower='python -c "import sys;print(sys.stdin.read().lower())"'
alias uuidstring='python -c "import uuid,sys; print(uuid.UUID(sys.stdin.read(32)))"'

function open-nautilus() {
    PWD=$(pwd)
    echo "Nautilus into $PWD"
    nautilus $PWD
}
alias nauty='open-nautilus'

alias doosh='du -sh'
alias doosh-list='du -h --max-depth=1'
alias doosh-list-sort='du -h --max-depth=1| sort -hrk1'

PROJECTS_HOME="$( dirname "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" )"

# Autobash User Section

# Autobash - End
