#!/bin/bash



# Autobash
alias srcbash='source ~/.bashrc'
alias edit-bash=$EDITOR' ~/.bashrc ~/.bash_aliases'
alias edit-bashaliases=$EDITOR' ~/.bash_aliases'
alias edit-bashrc=$EDITOR' ~/.bashrc'
alias anaconda3='bash --rcfile ~/.conda_bashrc3'
alias tolower='python -c "import sys;print(sys.stdin.read().lower())"'
alias uuidstring='python -c "import uuid,sys; print(uuid.UUID(sys.stdin.read(32)))"'
alias myip="wget -qO- http://ipecho.net/plain"

function open-nautilus() {
    PWD=$(pwd)
    echo "Nautilus into $PWD"
    nautilus $PWD
}
alias nauty='open-nautilus'

alias doosh='du -sh'
alias doosh-list='du -h --max-depth=1'
alias doosh-list-sort='du -h --max-depth=1| sort -hrk1'

PROJECTS_HOME="$( dirname "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" )"

# Autobash User Section

# Autobash - End

# project: autobash
alias cd-autobash='cd /home/'$USER'/autobash'
alias atom-autobash='atom -n /home/'$USER'/autobash /home/'$USER'/pytk'
alias cp-autobash='source /home/'$USER'/autobash/cp_autobash'

# autobash-tools
alias autobash-get-protemplates=$CONDA_DIR'/bin/python /home/'$USER'/autobash/tools/protemplates.py --local_directory /home/'$USER'/.autobash'
alias autobash-get-rmate=$CONDA_DIR'/bin/python /home/'$USER'/autobash/tools/rmate.py --local_directory /home/'$USER'/.autobash'
alias autobash-get-youtube-dl=$CONDA_DIR'/bin/python /home/'$USER'/autobash/tools/youtube-dl.py --local_directory /home/'$USER'/.autobash'
alias autobash-get-bazel=$CONDA_DIR'/bin/python /home/'$USER'/autobash/tools/bazel.py --local_directory /home/'$USER'/.autobash'


alias rgvpnlogin='pushd /home/'$USER'/vpn_config/nexocraft/Daiem.ali@87.138.226.29 && sudo openvpn --config /home/'$USER'/vpn_config/nexocraft/Daiem.ali@87.138.226.29/Daiem.ali@87.138.226.29.ovpn'
alias tolower='python -c "import sys;print(sys.stdin.read().lower(),end=\"\")"'
alias toupper='python -c "import sys;print(sys.stdin.read().upper(),end=\"\")"'
alias unescape='python -c "import sys;print(sys.stdin.read().encode().decode(\"unicode_escape\"),end=\"\")"'